# Generated by Django 4.2.2 on 2023-08-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
